import { isoAgo } from '@/lib/demo-utils';
import type { Lead } from '@/lib/types';

/**
 * Leads de demostración alineados con el contrato de AGT-NEG-CA
 * (prompts/01-negocio/ca.md): phone único, zonas activas, niveles y score 0-100.
 */
export const demoLeads: Lead[] = [
  {
    phone: '+5212283401122',
    name: 'María Fernanda',
    zona: 'Boca del Río',
    origen: 'meta_ads',
    nivel: 'kit_prueba',
    estado: 'negociando',
    estado_propuesta: 'vista',
    score: 84,
    nota: 'Escribió el mismo día. Gancho: condensación del vaso. Preguntó por entrega sábado 7 am.',
    valor_estimado: 480,
    creado_en: isoAgo(95),
    updated_at: isoAgo(18),
  },
  {
    phone: '+522281234567',
    name: 'Don Toño Guzmán',
    zona: 'Poza Rica',
    origen: 'instagram',
    nivel: 'hosteleria',
    estado: 'cerrado',
    estado_propuesta: 'aceptada',
    score: 92,
    nota: 'Fonda con merma de 3 garrafas/sem. Confirmó 3 garrafas de Hostelería para el sábado.',
    valor_estimado: 2250,
    creado_en: isoAgo(2100),
    updated_at: isoAgo(260),
  },
  {
    phone: '+522291572094',
    name: 'Restaurante El Muelle',
    zona: 'Veracruz Centro',
    origen: 'meta_ads',
    nivel: 'patronal_supremo',
    estado: 'en_oferta',
    estado_propuesta: 'enviada',
    score: 88,
    nota: '2+ niveles mencionados. Quedan 5 de 12 cupos del lote del centro.',
    valor_estimado: 6800,
    creado_en: isoAgo(320),
    updated_at: isoAgo(45),
  },
  {
    phone: '+522791138400',
    name: 'La Michoacana Palo Verde',
    zona: 'Xalapa',
    origen: 'google_ads',
    nivel: 'hosteleria',
    estado: 'negociando',
    estado_propuesta: 'enviada',
    score: 76,
    nota: 'Pide rendimiento por garrafa. Enviar caso de +65% por copeo.',
    valor_estimado: 3100,
    creado_en: isoAgo(410),
    updated_at: isoAgo(120),
  },
  {
    phone: '+522283004719',
    name: 'Karina Salas',
    zona: 'Boca del Río',
    origen: 'whatsapp_broadcast',
    nivel: 'kit_prueba',
    estado: 'nuevo',
    estado_propuesta: 'sin_enviar',
    score: 58,
    nota: 'Respondió al broadcast con "¿cómo funciona el Kit?". Falta anclaje de niveles.',
    valor_estimado: 230,
    creado_en: isoAgo(150),
    updated_at: isoAgo(40),
  },
  {
    phone: '+522921100853',
    name: 'Taquería Don Memo',
    zona: 'Coatzacoalcos',
    origen: 'referral',
    nivel: 'hosteleria',
    estado: 'en_oferta',
    estado_propuesta: 'vista',
    score: 81,
    nota: 'Referido por Don Toño. Lote Coatza casi agotado: prioridad alta.',
    valor_estimado: 2900,
    creado_en: isoAgo(260),
    updated_at: isoAgo(75),
  },
  {
    phone: '+522291888340',
    name: 'Hotel Marisol',
    zona: 'Veracruz Centro',
    origen: 'google_ads',
    nivel: 'patronal_supremo',
    estado: 'lista_espera',
    estado_propuesta: 'pausada',
    score: 45,
    nota: 'Zona sin cupo hasta el nuevo lote. En lista de espera sin inventar plazos.',
    valor_estimado: 5200,
    creado_en: isoAgo(900),
    updated_at: isoAgo(200),
  },
  {
    phone: '+522791201455',
    name: 'Cervecería El Gato',
    zona: 'Poza Rica',
    origen: 'meta_ads',
    nivel: 'hosteleria',
    estado: 'perdido',
    estado_propuesta: 'rechazada',
    score: 34,
    nota: 'Prefiere embotellado. Reintentar el próximo lote con prueba de copa gratis.',
    valor_estimado: 1800,
    creado_en: isoAgo(1400),
    updated_at: isoAgo(500),
  },
  {
    phone: '+522281953607',
    name: 'Paletería La Reyna',
    zona: 'Xalapa',
    origen: 'instagram',
    nivel: 'kit_prueba',
    estado: 'aceptado',
    estado_propuesta: 'aceptada',
    score: 79,
    nota: 'Aceptó Kit Prueba para empezar. Entrega sábado 7 am, 10 litros.',
    valor_estimado: 420,
    creado_en: isoAgo(700),
    updated_at: isoAgo(130),
  },
  {
    phone: '+529211068247',
    name: 'Comedor Doña Chole',
    zona: 'Coatzacoalcos',
    origen: 'whatsapp_broadcast',
    nivel: 'patronal_supremo',
    estado: 'nuevo',
    estado_propuesta: 'sin_enviar',
    score: 63,
    nota: 'Pregunta por precio a granel y horarios de la prensa. Anclar 3 niveles.',
    valor_estimado: 6400,
    creado_en: isoAgo(80),
    updated_at: isoAgo(25),
  },
];