import { isoAgo } from '@/lib/demo-utils';
import type { MediaAsset } from '@/lib/types';

/**
 * Activos de ejemplo generados por los agentes de Contenido (05-contenido):
 * AGT-CON-CC (creador), AGT-CON-CV (guionista), AGT-CON-HA (historias),
 * AGT-CON-RP (producto) y AGT-CON-VM (distribución de video).
 */
export const demoMediaAssets: MediaAsset[] = [
  {
    id: 'asset_01',
    titulo: 'La prensa no espera',
    tipo: 'reel_script',
    producto: 'torito_cacahuate',
    agente: 'AGT-CON-CV',
    copy: 'Coatzacoalcos: la prensa sale mañana 7 am y quedan 5 de 12 cupos. Torito de Cacahuate cremoso, lote fresco de esta semana. ¿Lo apartamos? TORITO',
    duracion_seg: 18,
    plataforma: 'IG / TikTok',
    texto_pantalla: ['LA PRENSA NO ESPERA', 'KIT HOY'],
    tags: ['escasez', 'torito', 'coatzacoalcos', 'hook'],
    creado_en: isoAgo(140),
  },
  {
    id: 'm_02',
    titulo: 'Condensación en el vaso',
    tipo: 'imagen',
    producto: 'jugo_cana',
    agente: 'AGT-CON-HA',
    copy: 'El vaso se empaña del frío antes de la casa el precio. Jugo de caña prensado en el momento, Veracruz puro.',
    plataforma: 'IG · 4:5',
    tags: ['sensorial', 'veracruz', 'condensación'],
    creado_en: isoAgo(210),
  },
  {
    id: 'asset_03',
    titulo: 'Escalera de 3 niveles para restaurantes',
    tipo: 'carrusel',
    producto: 'cafe',
    agente: 'AGT-CON-CC',
    copy: 'Café de olla con caña artesanal para tu carta. Patronal Supremo a granel · Hostelería +65% por copeo · Kit Prueba de entrada. Elige 1, te enseñamos la escalera. Escribe CAFÉ.',
    tags: ['b2b', 'hosteleria', 'anclaje', 'carrusel'],
    creado_en: isoAgo(300),
  },
  {
    id: 'asset_04',
    titulo: 'Kit Prueba · Coatzacoalcos',
    tipo: 'video',
    producto: 'torito_cacahuate',
    agente: 'AGT-CON-VM',
    copy: 'Jornada de prensad en vivo: crema, aroma a cacahuate y el hielo cayendo. Torito de Cacahuate de lote fresco.',
    duracion_seg: 32,
    plataforma: 'YouTube Shorts',
    tags: ['video', 'proceso', 'torito'],
    creado_en: isoAgo(380),
  },
  {
    id: 'asset_05',
    titulo: 'Torito cremoso de noche',
    tipo: 'reel_script',
    producto: 'coco',
    agente: 'AGT-CON-CV',
    copy: 'De noche, la crema del torito de coco se siente hasta el fondo del vaso. Digeria veracruzano, orgullo digestivo. Escribe COCO',
    duracion_seg: 15,
    plataforma: 'IG Reels',
    texto_pantalla: ['CREMOSO DE NOCHE', 'COCO HOY'],
    tags: ['coco', 'nocturno', 'cream'],
    creado_en: isoAgo(150),
  },
  {
    id: 'asset_06',
    titulo: 'Aguardiente veracruzano',
    tipo: 'imagen',
    producto: 'aguardiente',
    agente: 'AGT-CON-RP',
    copy: 'Aguardiente de caña de lote artesanal. Hecho en Veracruz, embotado con orgullo. Límite de lote por temporada.',
    tags: ['aguardiente', 'lote artesanal'],
    creado_en: isoAgo(420),
  },
  {
    id: 'asset_07',
    titulo: 'Café de olla con caña',
    tipo: 'carrusel',
    producto: 'cafe',
    agente: 'AGT-CON-HA',
    copy: 'El café de olla se endulza con caña prensada, no con azúcar. Historia de la receta en 4 disparos.',
    tags: ['café', 'receta', 'b2c'],
    creado_en: isoAgo(510),
  },
  {
    id: 'asset_08',
    titulo: 'Recorrido por la paila',
    tipo: 'video',
    producto: 'aguardiente',
    agente: 'AGT-CON-VM',
    copy: 'De la caña a la garrafa: recorrido por la paila del aguardiente. Solo 30 lotes por temporada.',
    duracion_seg: 58,
    plataforma: 'YouTube',
    tags: ['proceso', 'aguardiente', 'trailer'],
    creado_en: isoAgo(600),
  },
];