import { isoAgo } from '@/lib/demo-utils';
import type { MetricasEjecutivas } from '@/lib/types';

/**
 * Métricas ejecutivas de ejemplo basadas en el contrato de salida de
 * AGT-ADS-AL (prompts/03-ads/al.md): CR, CAC, AOV, ROAS, por zona y fugas.
 */
export const demoMetricas: MetricasEjecutivas = {
  periodo: '2026-06-29 a 2026-07-05',
  kpis: [
    {
      clave: 'cr',
      etiqueta: 'Tasa de Conversión',
      valor: 31.4,
      unidad: '%',
      tendencia: 4.2,
      semaforo: 'ok',
      nota: 'cerrados vs. leads calificados (ventana 7d)',
    },
    {
      clave: 'cac',
      etiqueta: 'Costo de Adquisición',
      valor: 41,
      unidad: 'MXN',
      tendencia: -8.1,
      semaforo: 'ok',
      nota: 'referenciado al LTV por nivel',
    },
    {
      clave: 'aov',
      etiqueta: 'Ticket Promedio (AOV)',
      valor: 385,
      unidad: 'MXN',
      tendencia: 12.4,
      semaforo: 'ok',
      nota: 'mezcla de Kit, Hostelería y Patronal',
    },
    {
      clave: 'roas',
      etiqueta: 'ROAS Global',
      valor: 3.42,
      unidad: 'x',
      tendencia: -0.18,
      semaforo: 'warn',
      nota: 'Meta retarget quemado en Coatzacoalcos',
    },
  ],
  por_zona: [
    { zona: 'Boca del Río', cac: 38, cvr: 33, roas: 3.9, cupos_vendidos: 8, cupos_disponibles: 4 },
    { zona: 'Veracruz Centro', cac: 41, cvr: 31, roas: 3.6, cupos_vendidos: 10, cupos_disponibles: 2 },
    { zona: 'Xalapa', cac: 44, cvr: 28, roas: 3.1, cupos_vendidos: 6, cupos_disponibles: 6 },
    { zona: 'Poza Rica', cac: 47, cvr: 27, roas: 2.9, cupos_vendidos: 4, cupos_disponibles: 8 },
    { zona: 'Coatzacoalcos', cac: 52, cvr: 24, roas: 2.6, cupos_vendidos: 5, cupos_disponibles: 7 },
  ],
  fugas: [
    {
      tipo: 'sin_respuesta_24h',
      costo: 480,
      accion: 'WT responder < 5 min dentro del horario 8–21 h',
    },
    {
      tipo: 'frecuencia_meta_2.9',
      costo: 210,
      accion: 'Pausar ad set de retarget en Coatzacoalcos hasta lote nuevo',
    },
  ],
  agentes: [
    {
      id: 'AGT-NEG-CA',
      nombre: 'Comercial / CRM',
      modulo: '01-Negocio',
      estado: 'ok',
      last_run: isoAgo(6),
      ejecuciones: 128,
      latencia_ms: 812,
      ultimo_mensaje: 'Pipeline actualizado: 12 leads nuevos hoy',
    },
    {
      id: 'AGT-NEG-WT',
      nombre: 'Ventas WhatsApp',
      modulo: '01-Negocio',
      estado: 'ok',
      last_run: isoAgo(3),
      ejecuciones: 214,
      latencia_ms: 645,
      ultimo_mensaje: 'Cierre confirmado: Don Toño, 3 garrafas Poza Rica',
    },
    {
      id: 'AGT-ADS-MA',
      nombre: 'Meta Ads Manager',
      modulo: '03-Ads',
      estado: 'ok',
      last_run: isoAgo(12),
      ejecuciones: 92,
      latencia_ms: 1240,
      ultimo_mensaje: 'Presupuesto Xalapa Kit +30% con semáforo verde',
    },
    {
      id: 'AGT-ADS-GA',
      nombre: 'Google Ads',
      modulo: '03-Ads',
      estado: 'ok',
      last_run: isoAgo(24),
      ejecuciones: 64,
      latencia_ms: 1380,
      ultimo_mensaje: 'Search + Display activos para hostelería',
    },
    {
      id: 'AGT-ADS-AL',
      nombre: 'Analista de Leads / ROAS',
      modulo: '03-Ads',
      estado: 'warn',
      last_run: isoAgo(41),
      ejecuciones: 57,
      latencia_ms: 1520,
      ultimo_mensaje: 'ROAS Coatzacoalcos 2.6: fuga de frecuencia detectada',
    },
    {
      id: 'AGT-SOC-MD',
      nombre: 'Moderador y Respuestas',
      modulo: '02-Social',
      estado: 'warn',
      last_run: isoAgo(22),
      ejecuciones: 340,
      latencia_ms: 512,
      ultimo_mensaje: '3 conversaciones en fila, 1 sin responder > 1 h',
    },
    {
      id: 'AGT-CON-VM',
      nombre: 'Distribución de Video',
      modulo: '05-Contenido',
      estado: 'error',
      last_run: isoAgo(180),
      ejecuciones: 38,
      latencia_ms: 4200,
      ultimo_mensaje: 'Webhook de publicación no respondió (timeout en Make)',
    },
  ],
};